// Code generated by file2byteslice. DO NOT EDIT.

package resources

var Config = []byte("{\r\n  \"screenWidth\": 640,\r\n  \"screenHeight\": 480,\r\n  \"title\": \"外星人入侵\",\r\n  \"bgColor\": {\r\n    \"r\": 230,\r\n    \"g\": 230,\r\n    \"b\": 230,\r\n    \"a\": 255\r\n  },\r\n  \"shipSpeedFactor\": 3,\r\n  \"bulletWidth\": 3,\r\n  \"bulletHeight\": 3,\r\n  \"bulletSpeedFactor\": 2,\r\n  \"maxBulletNum\": 20,\r\n  \"bulletInterval\": 50,\r\n  \"bulletColor\": {\r\n    \"r\": 80,\r\n    \"g\": 80,\r\n    \"b\": 80,\r\n    \"a\": 255\r\n  },\r\n  \"AlienSpeedFactor\": 2,\r\n  \"AlienInterval\": 4000,\r\n  \"TitleFontSize\": 20,\r\n  \"FontSize\": 20,\r\n  \"SmallFontSize\": 20,\r\n  \"FailNum\": 10,\r\n  \"SuccessNum\": 25\r\n}")
